version: '3.5'

services:
  db:
    image: yuntumg/artist-db:0.0.1
    container_name: artist-db
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artist
      MYSQL_USER: artist
      MYSQL_PASSWORD: artist

  app1:
    image: yuntumg/artist-app-manual:0.0.1
    container_name: artist-app-manual
    depends_on:
      - db
    ports:
      - "18080:8080"
    environment:
      JAR_TARGET: artist-0.0.1-SNAPSHOT.jar

  app2:
    image: yuntumg/artist-app-jib:0.0.1
    container_name: artist-app-jib
    depends_on:
      - db
    ports:
      - "18081:8080"

volumes:
  db:
    driver: local
