version: '3.5'

services:
  db:
    build: ./db
    image: artist-db:0.0.1
    container_name: artist-db
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artist
      MYSQL_USER: artist
      MYSQL_PASSWORD: artist
    networks:
      - default

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    image: artist-app:0.0.1
    container_name: artist-app
    depends_on:
      - db
    ports:
      - "18080:8080"
    environment:
      JAR_TARGET: artist-0.0.1-SNAPSHOT.jar
    networks:
      - default

volumes:
  db:
    driver: local

networks:
  default:
    name: artist-network
